# Project 3 — Titanic Survival Prediction (Real Dataset)

### Problem Statement
##### Predict whether a passenger survived the Titanic disaster based on:

* Age
* Sex
* Passenger Class (Pclass)
* Fare

**Target : Survived**

* 0 = Did Not Survive
* 1 = Survived

In [103]:
# Step 1: Import Libraries

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

In [104]:
 # Step 2: Load Dataset

df = pd.read_csv(r"D:\Python For DA & ML For DS\ML For DS\Self Learning\100_Days_GitHub_ML_Quotas\Titanic-Dataset.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [118]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",0,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",1,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",0,35.0,0,0,373450,8.0500,NaN,S

In [119]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    int64
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(6), object(4)
memory usage: 83.7+ KB

In [106]:
# Check missing values:

print(df.isnull().sum())

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [107]:
# Step 3: Handle Missing Values

df['Age'] = df['Age'].fillna(df['Age'].median())

In [108]:
# Step 4: Convert Text to Numbers ML models cannot understand text.

df['Sex'] = df['Sex'].map({
    'male':0,
    'female':1
})

In [109]:
 # Step 5: Select Features

X = df[['Pclass', 'Sex', 'Age', 'Fare']]
y = df['Survived']

In [110]:
# Step 6: Train-Test Split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [111]:
 # Step 7: Train Model

model = RandomForestClassifier()

model.fit(X_train, y_train)

RandomForestClassifier()

In [112]:
# Step 8: Prediction

y_pred = model.predict(X_test)

In [113]:
# Step 9: Accuracy

acc = accuracy_score(y_test, y_pred)

print("Accuracy:", acc)

Accuracy: 0.7988826815642458

In [116]:
 # Step 10: Feature Importance

importance = model.feature_importances_

features = ['Pclass', 'Sex', 'Age', 'Fare']

for f, imp in zip(features, importance):
    print(f, ":", imp)

Pclass : 0.10306258591675439
Sex : 0.29713222845441145
Age : 0.27428481626339585
Fare : 0.3255203693654382

##  Interview Questions

Answer after running:

1. Why did we fill missing values in Age?

2. Why did we convert Sex into numbers?

3. Which feature was most important?

4. Why can't Random Forest directly use text values?

5. If a new passenger is:

* Pclass = 1
* Sex = Female
* Age = 25
* Fare = 100

How would you predict survival?

In [ ]:
# 1. Most ML models cannot handle missing values, so we fill them to avoid errors and make training possible.

# 2. ML models work with numerical values, not text values.

# 3. Fare was the most important feature.

# 4. Random Forest performs mathematical operations and splits on numeric values, so text must be converted into numbers first.

# 5. new_passenger = pd.DataFrame({
#     'Pclass': [1],
#     'Sex': [1],      # Female = 1
#     'Age': [25],
#     'Fare': [100]
# })

# print(model.predict(new_passenger))

# The model will likely predict:

# Survived (1)